version: '3'
services:
  php80:
    build: docker/php80
    volumes:
      - .:/app
    working_dir: /app

  php81:
    build: docker/php81
    volumes:
      - .:/app
    working_dir: /app
  php82:
    build: docker/php82
    volumes:
      - .:/app
    working_dir: /app
