services:
  php82:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        PHP_VERSION: "8.2"
    volumes:
      - .:/app
    working_dir: /app

  php83:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        PHP_VERSION: "8.3"
    volumes:
      - .:/app
    working_dir: /app

  php84:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        PHP_VERSION: "8.4"
    volumes:
      - .:/app
    working_dir: /app

  php85:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        PHP_VERSION: "8.5"
    volumes:
      - .:/app
    working_dir: /app
