#!/usr/bin/env php
<?php
declare (strict_types=1);

foreach ([__DIR__ . '/../../autoload.php', __DIR__ . '/../vendor/autoload.php', __DIR__ . '/vendor/autoload.php'] as $file) {
    if (file_exists($file)) {
        define('PHPDEL_COMPOSER_INSTALL', $file);

        break;
    }
}

unset($file);

if (!defined('PHPDEL_COMPOSER_INSTALL')) {
    fwrite(
        STDERR,
        'You need to set up the project dependencies using Composer:' . PHP_EOL . PHP_EOL .
        '    composer install' . PHP_EOL . PHP_EOL .
        'You can learn all about Composer on https://getcomposer.org/.' . PHP_EOL
    );

    die(1);
}

require PHPDEL_COMPOSER_INSTALL;

$app = new PHPDel\Application(new \League\CLImate\CLImate());
$app->main();
